---
- hosts: hana
  #remote_user: root
  roles:
          - { role: redhat_sap.sap_rhsm }
          - { role: redhat_sap.sap_hana_mediacheck }
          - { role: redhat_sap.sap_hostagent }
          - { role: linux-system-roles.timesync }
          - { role: linux-system-roles.storage }
          - { role: sap-preconfigure }
          - { role: sap-hana-preconfigure }
          - { role: redhat_sap.sap_hana_deployment }
          - { role: redhat_sap.sap_hana_hsr }
          - { role: redhat_sap.sap_hana_ha_pacemaker }
...
