- name: Set up Azure credentials
  hosts: localhost
  connection: local
  tasks:
    - name: Include Azure credentials
      include_vars: files/azure_cred.yml

    - name: Log into Azure
      command: >
                az login -u "{{ azure_account }}" -p "{{ azure_secret }}"

    - name: Create a service principal
      command: >
                az ad sp create-for-rbac --name ServicePrincipalHana
      register: ad_info
    - set_fact:
        ad_vars: "{{ ad_info.stdout | from_json }}"

    - name: Get Azure account information
      command: >
                az account show
      register: account_info
    - set_fact:
        account_vars: "{{ account_info.stdout | from_json }}"

    - name: Insert Azure credentials configuration in /root/.azure/credentials
      blockinfile:
        path: /root/.azure/credentials
        create: yes
        block: |
          [default]
          subscription_id={{ account_vars.id }}
          client_id={{ ad_vars.appId }}
          secret={{ ad_vars.password }}
          tenant={{ ad_vars.tenant }}

    - name: Verify the Azure credentials by listing resource groups
      azure_rm_resourcegroup_facts:
      register: output
    - debug: var=output
